---
# CPU Performance Optimizations
- name: Install irqbalance for interrupt distribution
  apt:
    name: irqbalance
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Enable and start irqbalance service
  systemd:
    name: irqbalance
    enabled: yes
    state: started

- name: Install cpufrequtils for CPU governor management
  apt:
    name: cpufrequtils
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Set CPU governor to ondemand for dynamic scaling
  shell: |
    for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
      if [ -f "$cpu" ]; then
        echo ondemand > "$cpu"
      fi
    done
  register: cpu_governor_result
  changed_when: false

- name: Configure CPU governor to persist across reboots (set to ondemand for flexibility)
  lineinfile:
    path: /etc/default/cpufrequtils
    line: 'GOVERNOR="ondemand"'
    create: yes
    backup: yes

# Memory and Swap Optimization
- name: Configure kernel parameters for AI workloads
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-ai-performance.conf
    reload: yes
  loop:
    # Memory management
    - { key: "vm.swappiness", value: "1" }           # Reduce swap usage
    - { key: "vm.vfs_cache_pressure", value: "50" }  # Keep more cache
    - { key: "vm.dirty_ratio", value: "15" }         # Reduce dirty pages
    - { key: "vm.dirty_background_ratio", value: "5" } # Background writeback
    - { key: "vm.overcommit_memory", value: "1" }    # Allow memory overcommit
    - { key: "vm.overcommit_ratio", value: "80" }    # Overcommit threshold
    # CPU scheduling
    - { key: "kernel.sched_autogroup_enabled", value: "0" }       # Disable autogroup
    # Performance
    - { key: "kernel.numa_balancing", value: "0" }   # Disable NUMA balancing for VMs
    - { key: "kernel.randomize_va_space", value: "1" } # Reduce randomization overhead

# I/O Scheduler Optimization
- name: Check available I/O schedulers
  shell: cat /sys/block/$(lsblk -no pkname $(findmnt -no SOURCE /) | head -1)/queue/scheduler
  register: io_scheduler_check
  changed_when: false

- name: Set I/O scheduler to mq-deadline (best for VMs)
  shell: |
    for disk in /sys/block/*/queue/scheduler; do
      if [ -f "$disk" ] && grep -q "mq-deadline" "$disk"; then
        echo mq-deadline > "$disk"
      fi
    done
  when: "'mq-deadline' in io_scheduler_check.stdout"
  register: io_scheduler_result
  changed_when: false

- name: Configure I/O scheduler persistence
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash elevator=mq-deadline"'
    backup: yes
  register: grub_config
  notify: update grub

# Transparent Huge Pages optimization
- name: Check THP status
  command: cat /sys/kernel/mm/transparent_hugepage/enabled
  register: thp_status
  changed_when: false

- name: Set THP to madvise (better for memory-intensive AI)
  shell: echo madvise > /sys/kernel/mm/transparent_hugepage/enabled
  when: "'[madvise]' not in thp_status.stdout"
  register: thp_result
  changed_when: thp_result.rc == 0

- name: Configure THP persistence
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash elevator=mq-deadline transparent_hugepage=madvise"'
    backup: yes
  register: grub_config_thp
  notify: update grub

# Final GRUB configuration with frequency scaling enabled
- name: Configure GRUB with optimizations but keep frequency scaling
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash elevator=mq-deadline transparent_hugepage=madvise"'
    backup: yes
  register: grub_config_final
  notify: update grub

- name: Display AI performance optimization status
  debug:
    msg:
      - "AI Performance optimizations applied:"
      - "- CPU Governor: ondemand (dynamic scaling enabled)"
      - "- IRQ Balancing: enabled"
      - "- Swappiness: 1 (minimal swap usage)"
      - "- I/O Scheduler: mq-deadline"
      - "- Transparent Huge Pages: madvise"
      - "- Memory overcommit: enabled"
      - "- NUMA balancing: disabled"
      - "- CPU frequency scaling: enabled (use cpufreq-set to change profiles)"
      - "Note: Reboot required for full optimization"