---
# Disable unnecessary services for AI workloads while preserving DNS resolution
# DNS is handled by systemd-resolved.service, not avahi-daemon

# High Priority Services to Disable (Definite disable)
- name: Stop and disable bluetooth service
  systemd:
    name: bluetooth.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable blueman-mechanism service
  systemd:
    name: blueman-mechanism.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable CUPS printing service
  systemd:
    name: cups.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable CUPS browser service
  systemd:
    name: cups-browsed.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable avahi-daemon (mDNS/service discovery)
  systemd:
    name: avahi-daemon.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable ModemManager service
  systemd:
    name: ModemManager.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable power-profiles-daemon (conflicts with tuned)
  systemd:
    name: power-profiles-daemon.service
    enabled: no
    state: stopped
  ignore_errors: yes

# Medium Priority Services to Disable (Likely safe)
- name: Stop and disable whoopsie error reporting
  systemd:
    name: whoopsie.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable apport crash reporting
  systemd:
    name: apport.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable firmware update daemon
  systemd:
    name: fwupd.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable kernel error reporting
  systemd:
    name: kerneloops.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Stop and disable anacron scheduled tasks
  systemd:
    name: anacron.service
    enabled: no
    state: stopped
  ignore_errors: yes

# Disable unnecessary desktop services
- name: Disable speech-dispatcher service
  systemd:
    name: speech-dispatcher.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Remove evolution packages
  apt:
    name:
      - evolution-data-server
      - evolution-data-server-common
    state: absent
    purge: yes
  ignore_errors: yes

- name: Disable blueman autostart (GUI bluetooth manager)
  file:
    path: /etc/xdg/autostart/blueman.desktop
    state: absent
  ignore_errors: yes

- name: Disable evolution autostart
  file:
    path: /etc/xdg/autostart/evolution-data-server.desktop
    state: absent
  ignore_errors: yes

- name: Disable at-spi accessibility services autostart
  file:
    path: /etc/xdg/autostart/at-spi-dbus-bus.desktop
    state: absent
  ignore_errors: yes

- name: Kill existing unnecessary desktop processes
  shell: |
    pkill -f speech-dispatcher || true
    pkill -f evolution-alarm-notify || true
    pkill -f evolution-source-registry || true
    pkill -f evolution-calendar-factory || true
    pkill -f evolution-addressbook-factory || true
    pkill -f at-spi-bus-launcher || true
    pkill -f blueman-applet || true
  ignore_errors: yes
  changed_when: false

# Test DNS resolution after disabling services
- name: Test DNS resolution after service optimization
  command: nslookup google.com
  register: dns_test
  changed_when: false
  failed_when: dns_test.rc != 0

- name: Verify systemd-resolved is still running
  systemd:
    name: systemd-resolved.service
    state: started
  register: resolved_check

- name: Display service optimization results
  debug:
    msg:
      - "Service optimization completed:"
      - "- Disabled: bluetooth, cups, avahi-daemon, ModemManager, power-profiles-daemon"
      - "- Disabled: whoopsie, apport, fwupd, kerneloops, anacron"
      - "- Disabled: speech-dispatcher, evolution-data-server, blueman-applet"
      - "- Disabled: at-spi accessibility services"
      - "- DNS resolution: {{ 'WORKING' if dns_test.rc == 0 else 'FAILED' }}"
      - "- systemd-resolved: {{ resolved_check.state }}"
      - "Estimated resource savings: ~80-200MB RAM, ~5-10% CPU reduction"